### ISSUE TITLE
Fout in readme: de links in lijst van beleidsterreinen kloppen niet 

### ISSUE THREAD

**Issue by markbacker** [Gemeente-Delft/Gemeentelijk-Gegevensmodel#15]
Op de [readme](https://github.com/gemeente-delft/Gemeentelijk-Gegevensmodel/) van github zie ik het beleidsdomein Inburgering niet meer. Wel een nieuw domein [Dak- en thuislozen](https://gemeente-delft.github.io/Gemeentelijk-Gegevensmodel/domeinen/participatie/) dat verwijst naar participatie.

Het menu op github pages klopt - snel bekeken - wel.

**Comment by AshkanA** [comment]
Goedemorgen Mark, 

Dank voor de feedback. Inburgering is zojuist weer toegevoegd. Dak en thuislozen is voor nu (nog) onderdeel van participatie 

Grt
